language: node_js

version: 1.0

node_js: "10"

cache:
  directories:
    - node_modules

script:
  - yarn lint
  - yarn stylelint
  - yarn test --coverage
  - yarn build:docs
  - yarn build:rollup

after_success:
  - bash < (curl -s https://codecov.io/bash)

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: false
    on:
      branch: master
    local_dir: styleguide
  - provider: npm
    edge: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      branch: master

notifications:
  email: false