language: node_js

version: 1.0

node_js: "10"

cache:
  directories:
    - node_modules

script:
  - yarn lint
  - yarn test
  - yarn build:style

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
    local_dir: styleguide
  - provider: npm
    edge: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      branch: master