export default {
  '--dayWidth': '38px',
  '--dayHeight': 'var(--dayWidth)',
  '--basePadding': '6px',
  '--innerPadding': '16px',
  '--innerWidth': '280px',
  '--datePickerWidth': 'calc(var(--innerWidth) + var(--innerPadding) * 2)',
  '--borderRadius': '4px',
  '--gridHeight': '247px',
  '--inputHeight': '25px',
  '--baseColor': 'black',
  '--gray': 'rgba(0, 0, 0, 0.38)',
  '--lightGray': 'rgba(0, 0, 0, 0.08)',
  '--green': '#43a047',
  '--disabled': 'var(--gray)',
  '--otherMonthColor': 'var(--lightGray)',
  '--active': 'var(--green)',
  '--hoverColor': 'var(--lightGray)',
  '--headerBgColor': 'var(--green)',
  '--headerTextColor': 'white',
  '--weekendColor': 'red',
  '--highlightColor': 'lightblue',
};
